### ISSUE TITLE
constantly reloads

### ISSUE THREAD

**Issue by Ginji-san** [Onestay/CR-Unblocker#32]
constantly reloads and tries to switch to america but it doesn't work.

**Comment by Onestay** [comment]
I'm aware of the issue and currently look into what is causing it.

**Comment by Mast3rwaf1z** [comment]
Any status update? i'd like to get back to binging Fate/UBD

**Comment by Onestay** [comment]
We have identified the issue and pushed a fix. I've just deployed the newest version to the chrome webstore. It should take about 20-50 minutes until it's published.

**Comment by Mast3rwaf1z** [comment]
great, thanks man

**Comment by Mast3rwaf1z** [comment]
seems this war won't end so easily... i still can't get on

**Comment by Onestay** [comment]
The new version is published. Try heading to chrome://extensions/ , enable developer mode and click on the button to update your extensions manually

**Comment by Mast3rwaf1z** [comment]
i have but even with the new version it still won't let me onto the american site

**Comment by Bazalia** [comment]
It worked with me.

**Comment by fukuokabernd** [comment]
Doesn't work for me neither. Constant reloads with version 2.2.1, the region stays at my home country.

**Comment by Onestay** [comment]
Yea, we are aware. Crunchyroll is currently changing some stuff with how the session is set. For now, to stop the reloading either uninstall the extension or turn off region switching in the dashboard.
The original reason why we had that issue was because the cookie was renamed from sess_id to session_id to set the session, however now we are not quite sure what is causing the reload. I'll keep up updated.

**Comment by Mast3rwaf1z** [comment]
Meh, it's alright, i'm actually studying for once instead

**Comment by Onestay** [comment]
Alright, I have pushed another version upgrade which should really fix it now.
Hopefully

**Comment by Mast3rwaf1z** [comment]
alright it's finally working for me, thanks!

**Comment by Onestay** [comment]
Alright, since I haven't received any further reports I guess it's working now.
I'm gonna close the issue.
